### ISSUE TITLE
Relationship between tablet() and mobile() is confusing

### ISSUE THREAD

**Issue by oschwald** [oalders/http-browserdetect#90]
Currently, the test for mobile appears to explicitly include some tablets, but it does not include everything in `tablet()`. The documentations for `mobile()` says, "Returns true if the browser appears to belong to a handheld device." From this, it is not clear if `tablet()` is supposed to be a subset of `mobile()` or if they two are supposed to be (mostly) mutually exclusive.

**Comment by andrewmoise** [comment]
I think the crux of the matter is discussed in the article attached to #38:

http://googlewebmastercentral.blogspot.co.uk/2011/03/mo-better-to-also-detect-mobile-user.html

"tablet users usually prefer the full desktop version over the mobile equivalent. If your site matches 'android' and then automatically redirects users, you may be forcing Android tablet users into a sub-optimal experience."

FWIW, my preferred working definition of the "mobile" test would be, "is this a device where the mobile version of a web site is appropriate to present instead of the desktop version"?

**Comment by andrewmoise** [comment]
I believe this has been resolved; as of v3.0 "tablet" and "mobile" are mutually exclusive. Tablets have tablet() true and mobile() false, and only devices that probably want the mobile version of your web site (phones, handheld game systems, etc.) have mobile() true.
